apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-graphene-secure-worker
  labels:
    app: tasker-graphene-secure-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-graphene-secure-worker
  template:
    metadata:
      labels:
        app: tasker-graphene-secure-worker
    spec:
      volumes:
        - name: aesmsocket
          hostPath:
            path: /var/run/aesmd/aesm.socket
            type: Socket
        - name: nfs-volume
          nfs:
            # URL for the NFS server
            server: 10.99.73.22
            path: /
        - name: gfs-volume
          hostPath:
            path: /mnt
      containers:
        - name: tasker
          image: cwidanage/tasker-graphene:0.02
          command: ["/bin/sh", "-c"]
          args:
            [
              "cd /root/graphene/ && make && cd /root/graphene-bwa && make clean && make SGX=1 && /sgx-tasks/build/applications/genomeseq/unsecworker tcp://tasker-server-worker:5050 secure_graphene",
            ]
          env:
            - name: ENV_ROOT_PATH
              value: "/data/"
          volumeMounts:
            - name: gfs-volume
              mountPath: /data
            - mountPath: /var/run/aesmd/aesm.socket
              name: aesmsocket
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 1
              memory: 6G
