kind: Service
apiVersion: v1
metadata:
  name: tasker-server-client
spec:
  type: NodePort
  selector:
    app: tasker-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31920
      name: clients
---
kind: Service
apiVersion: v1
metadata:
  name: tasker-server-worker
spec:
  type: ClusterIP
  selector:
    app: tasker-server
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: workers
