apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-server
  labels:
    app: tasker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-server
  template:
    metadata:
      labels:
        app: tasker-server
    spec:
      volumes:
        - name: nfs-volume
          nfs:
            # URL for the NFS server
            server: 10.99.73.22
            path: /
        - name: gfs-volume
          hostPath:
            path: /mnt
        - name: local
          hostPath:
            path: /data
            type: DirectoryOrCreate
      containers:
        - name: tasker
          image: cwidanage/tasker:0.49
          command: ["/bin/sh", "-c", "cd /sgx-tasks/ && git pull && cd /sgx-tasks/build && make && /sgx-tasks/build/applications/genomeseq/server" ]
          ports:
            - containerPort: 5000
            - containerPort: 5050
          args: []
          env:
            - name: ENV_ROOT_PATH
              # this is the default path client checks for indexing genome data. So that data needs to be here.
              value: "/data/"
          volumeMounts:
            - name: gfs-volume
              mountPath: /gfs
            - name: local
              mountPath: /data
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 5G
            # requests:
            #   cpu: 0.5
            #   memory: 3G
---
