apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-server
  labels:
    app: tasker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-server
  template:
    metadata:
      labels:
        app: tasker-server
    spec:
      volumes:
        - name: nfs-volume
          nfs:
            # URL for the NFS server
            server: 10.99.73.22
            path: /
        - name: gfs-volume
          hostPath:
            path: /mnt
      containers:
        - name: tasker
          image: cwidanage/tasker:0.49
          command: ["/bin/sh", "-c"]
          args: ["cd /sgx-tasks/ && git pull && cd /sgx-tasks/build && make && /sgx-tasks/build/applications/genomeseq/server"]
          # command: ["/sgx-tasks/build/applications/genomeseq/server"]
          ports:
            - containerPort: 5000
            - containerPort: 5050
          args: []
          env:
            - name: ENV_ROOT_PATH
              value: "/data/"
          volumeMounts:
            - name: gfs-volume
              mountPath: /data
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.2
              memory: 1G
            requests:
              cpu: 0.1
              memory: 256M
---
kind: Service
apiVersion: v1
metadata:
  name: tasker-server-client
spec:
  type: NodePort
  selector:
    app: tasker-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31920
      name: clients
---
kind: Service
apiVersion: v1
metadata:
  name: tasker-server-worker
spec:
  type: ClusterIP
  selector:
    app: tasker-server
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: workers
