apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-graphene-secure-worker
  labels:
    app: tasker-graphene-secure-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-graphene-secure-worker
  template:
    metadata:
      labels:
        app: tasker-graphene-secure-worker
    spec:
      volumes:
        - name: aesmsocket
          hostPath:
            path: /var/run/aesmd/aesm.socket
            type: Socket
        - name: nfs-volume
          nfs:
            # URL for the NFS server
            server: 10.99.73.22
            path: /
      containers:
        - name: tasker
          image: cwidanage/graphene-bwa:0.01
          command: ["/bin/sh", "-c"]
          args:
            [
              "cd /root/graphene/ && make && cd /root/graphene-bwa && SGX=1 ./pal_loader bwa",
            ]
          env:
            - name: ENV_ROOT_PATH
              value: "/data/"
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
            - mountPath: /var/run/aesmd/aesm.socket
              name: aesmsocket
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 1
              memory: 6G
