apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-secure-worker
  labels:
    app: tasker-secure-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-secure-worker
  template:
    metadata:
      labels:
        app: tasker-secure-worker
    spec:
      volumes:
        - name: aesmsocket
          hostPath:
            path: /var/run/aesmd/aesm.socket
            type: Socket
        - name: nfs-volume
          nfs:
            # URL for the NFS server
            server: 10.99.73.22
            path: /
      containers:
        - name: tasker
          image: cwidanage/tasker:0.31
          command:
            [
              "/sgx-tasks/build/applications/genomeseq/dida-sgx/sample/DIDA/didasgx",
            ]
          args: ["tcp://tasker-server-worker:5050"]
          env:
            - name: ENV_ROOT_PATH
              value: "/data/"
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/aesmd/aesm.socket
              name: aesmsocket
          resources:
            limits:
              cpu: 1
              memory: 4G
