apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-worker
  labels:
    app: tasker-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-worker
  template:
    metadata:
      labels:
        app: tasker-worker
    spec:
      containers:
        - name: tasker
          image: cwidanage/tasker:0.07
          command: ["/sgx-tasks/build/task"]
          args: ["tcp://tasker-server-worker:5050"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 4G
