apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-worker
  labels:
    app: tasker-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-worker
  template:
    metadata:
      labels:
        app: tasker-worker
    spec:
      containers:
        - name: tasker
          image: cwidanage/tasker:0.03
          command: ["/sgx-tasks/build/task"]
          args:
            ["worker123", "tcp://tasker-server-worker:5050"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 5G
---
kind: Service
apiVersion: v1
metadata:
  name: tasker-server
spec:
  type: NodePort
  selector:
    app: tasker-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: clients
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: workers
